UI/Pages/Bookings/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BO.Models;
using Service.IService;
using Service;

namespace UI.Pages.Bookings
{
    public class DetailsModel : PageModel
    {
        private readonly IBookingService _bookingService;

        public DetailsModel(IBookingService bookingService)
        {
            _bookingService = bookingService;
        }

        public  Booking Booking { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = _bookingService.GetById(id);
            if (booking == null)
            {
                return NotFound();
            }
            else 
            {
                Booking = booking;
            }
            return Page();
        }
    }
}

UI/Pages/Products/Details.cshtml.cs
using BO.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis;
using Microsoft.Extensions.Configuration.UserSecrets;
using Service.IService;
using System;

namespace UI.Pages.Products
{
    public class DetailsModel : PageModel
    {
        [BindProperty]
        public Product Product { get; set; }
        [BindProperty]
        public bool IsRegistered { get; set; } = true;
        [BindProperty]
        public int BookedCount { get; set; }

        private readonly IProductService _productService;
        private readonly IBookingService _bookingService;

        public DetailsModel(IProductService productService, IBookingService bookingService)
        {
            _productService = productService;
            _bookingService = bookingService;
        }

        public IActionResult OnGet(string productId)
        {
            try
            {
                Guid guid = Guid.Parse(productId);
                var product = _productService.GetProductById(guid, true);
                
                if (product == null)
                {
                    return RedirectToPage("/Error");
                }
                Product = product;

                //var userId = HttpContext.Session.GetString("Id");

                List<Booking> bookings = _bookingService.GetBookingsByProductId(guid) ?? new();
                var book = bookings?.FirstOrDefault(x => x.CustomerId.Equals(Guid.Parse("314F3DE7-ED73-4B08-AAD6-C2CCBECD32C2"))) ?? null;
                IsRegistered = book != null;
                BookedCount = bookings.Count;
                return Page();
            }
            catch (Exception)
            {
                return RedirectToPage("/Error");
                throw;
            }

        }

        public IActionResult OnPostBooking(Guid id)
        {
            var product = _productService.GetProductById(id);
            if (product == null)
            {
                return RedirectToPage("/Error");
            }

            //string? uid = HttpContext.Session.GetString("Id");
            string uid = "314F3DE7-ED73-4B08-AAD6-C2CCBECD32C2";
            if (uid == null)
            {
                return RedirectToPage("/Error");
            }

            var newBooking = new Booking()
            {
                Id = Guid.NewGuid(),
                CustomerId = Guid.Parse(uid),
                ProductId = product.Id,
                CreatedAt = DateTime.Now
            };

            var isSuccess = _bookingService.CreateBooking(newBooking);
            if (isSuccess)
            {

                ViewData["bookingMessage"] = "Booked successfully";
                return RedirectToPage($"/Products/Details", id.ToString());
            }
            else
            {
                return RedirectToPage("/Error");
            }
        }
    }
}

UI/Pages/Projects/AgencyProjectDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BO.Models;
using Service.IService;

namespace UI.Pages.Projects
{
    public class AgencyProjectDetailsModel : PageModel
    {
        private readonly IProjectService _projectService;
        private readonly IProductService _productService;

        public AgencyProjectDetailsModel(IProjectService projectService, IProductService productService)
        {
            _projectService = projectService;
            _productService = productService;
        }

        public Project Project { get; set; } = default!; 
        public IList<Product>? Products { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = _projectService.GetById(id);
            if (project == null)
            {
                return NotFound();
            }
            else 
            {
                Products = _productService.GetByProjectId(id);
                Project = project;
            }
            return Page();
        }
    }
}

UI/Pages/Projects/AgencyViewProjectList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BO.Models;
using Service.IService;

namespace UI.Pages.Projects
{
    public class AgencyViewProjectListModel : PageModel
    {
        private readonly IProjectService _projectService;

        public AgencyViewProjectListModel(IProjectService projectService)
        {
            _projectService = projectService;
        }
        [BindProperty]
        public string SearchKey { get; set; }

        public IList<Project> Project { get;set; } = default!;

        public async Task OnGetAsync()
        {
            Project = _projectService.GetProjects();
        }
        public IActionResult OnPost()
        {
            if (SearchKey == null)
            {
                Project = _projectService.GetProjects();
                return Page();
            }
            else
            {
                Project = new List<Project>();
                Project = _projectService.GetByProjectTitle(SearchKey);
            }

            return Page();
        }
        public IActionResult OnPostOnApprove(Guid id)
        {
            _projectService.ApproveProject(id);

            Project = _projectService.GetProjects();
            return Page();
        }
    }
}

UI/Pages/Projects/CustomerHistory.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BO.Models;
using Service.IService;
using System.Runtime.CompilerServices;

namespace UI.Pages.Projects
{
    public class CustomerHistoryModel : PageModel
    {
        private readonly IProjectService _projectService;
        private readonly IBookingService _bookingService;
        public CustomerHistoryModel(IProjectService projectService, IBookingService bookingService)
        {
            _projectService = projectService;
            _bookingService = bookingService;
        }

        public IList<Project> Project { get; set; } = default!;
        public IList<Booking> Booking { get; set; } = default!;

        public async Task OnGetAsync()
        {
            Project = _projectService.GetProjectsByInvestorId(Guid.Parse(HttpContext.Session.GetString("Id")));

            Booking = _bookingService.GetBookingsByCustomerId(Guid.Parse(HttpContext.Session.GetString("Id")));
        }
    }
}

UI/Pages/Projects/Details.cshtml.cs
using BO.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Service.IService;

namespace UI.Pages.Projects
{
    public class DetailsModel : PageModel
    {
        [BindProperty]
        public Project? Project { get; set; }
        
        private readonly IProjectService service;

        public DetailsModel(IProjectService service)
        {
            this.service = service;
        }

        public IActionResult OnGet(string projectId)
        {
            try
            {
                Guid guid = Guid.Parse(projectId);
                Project = service.GetById(guid);
                if (Project == null)
                {
                    return RedirectToPage("/Error");
                }
                return Page();
            }
            catch (Exception)
            {
                return RedirectToPage("/Error");
            }
        }
    }
}

UI/Pages/Projects/InvestorCreateProjectProducts.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using BO.Models;
using Service.IService;

namespace UI.Pages.Projects
{
    public class InvestorCreateProjectProductsModel : PageModel
    {
        private readonly IProjectService _projectService;
        private readonly IProductService _productService;

        public InvestorCreateProjectProductsModel(IProjectService projectService ,IProductService productService)
        {
            _projectService = projectService;
            _productService = productService;
        }

        [BindProperty]
        public Project Project { get; set; }

        [BindProperty]
        public List<Product> Products { get; set; }

        public void OnGet()
        {
            Products = new List<Product> { new Product() }; // Add an initial product
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            Project.Id = Guid.NewGuid();
            //wating for userId from session login
            Project.InvestorId = Guid.Parse(HttpContext.Session.GetString("Id"));

            Project.ProjectStatus = "Chờ duyệt";
            Project.CreatedAt = DateTime.Now;

            _projectService.CreateProject(Project);

            foreach (var product in Products)
            {
                product.Id = Guid.NewGuid();
                product.ProjectId = Project.Id; // Assign projectId to products

                // waiting for userid from session login
                product.InvestorId = Guid.Parse(HttpContext.Session.GetString("Id"));

                product.CreatedAt = DateTime.Now;

                _productService.CreateProduct(product);
            };

            //waiting for return page
            return RedirectToPage("./ProjectsList");
        }
    }
}

UI/Pages/Projects/ProjectDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BO.Models;
using Service.IService;
using System.Runtime.CompilerServices;

namespace UI.Pages.Projects
{
    public class CustomerProjectDetailsModel : PageModel
    {
        private readonly IProjectService _projectService;
        private readonly IProductService _productService;

        public CustomerProjectDetailsModel(IProjectService projectService, IProductService productService)
        {
            _productService = productService;
            _projectService = projectService;
        }

        public Project Project { get; set; } = default!;
        public List<Product> Products { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = _projectService.GetById(id);
            if (project == null)
            {
                return NotFound();
            }
            else 
            {
                Project = project;
                var products = _productService.GetByProjectId(project.Id);
                Products = products;
            }
            return Page();
        }
    }
}

UI/Pages/Projects/ProjectsList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BO.Models;
using Service.IService;
using System.Runtime.CompilerServices;

namespace UI.Pages.Projects
{
    public class CustomerProjectsListModel : PageModel
    {
        private readonly IProjectService _projectService;
        private readonly IUserService _userService;
        public CustomerProjectsListModel(IProjectService projectService, IUserService userService)
        {
            _projectService = projectService;
            _userService = userService;
        }
        [BindProperty]
        public string SearchKey { get; set; }
        public IList<Project> Project { get;set; } = default!;

        public async Task OnGetAsync()
        {
            Project = _projectService.GetProjectsByStatus();
        }
        public IActionResult OnPost()
        {
            if (SearchKey == null)
            {
                Project = _projectService.GetProjectsByStatus();
                return Page();
            }
            else
            {
                Project = new List<Project>();
                Project = _projectService.GetByProjectTitle(SearchKey);
            }

            return Page();
        }
    }
}

UI/Pages/Projects/AgencyProjectDetails.cshtml
@page
@model UI.Pages.Projects.AgencyProjectDetailsModel

@{
    ViewData["Title"] = "AgencyProjectDetails";
}

<h1>Chi tiet du an</h1>

<div>
    <a asp-page="./AgencyViewProjectList">Back to List</a>
</div>

<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayName("Địa chỉ")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.ProjectLocation)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Ngày bắt đầu")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Ngày kết thúc")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Tên dự án")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.ProjectTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Mô tả")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.ProjectContent)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Trạng thái")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.ProjectStatus)
        </dd>
    </dl>
</div>

<h2>Danh sách bất động sản</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Tên nhà")
            </th>
            <th>
                @Html.DisplayName("địa chỉ")
            </th>
            <th>
                @Html.DisplayName("Mô tả")
            </th>
            <th>
                @Html.DisplayName("Giá trị")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Products)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>

                <td>
                    <a asp-page="/Bookings/AgencyViewBookingOfProduct" asp-route-id="@item.Id">Chi tiết Booking</a> |
                </td>
            </tr>
        }
    </tbody>
</table>

UI/Pages/Projects/AgencyViewProjectList.cshtml
@page
@model UI.Pages.Projects.AgencyViewProjectListModel

@{
    ViewData["Title"] = "AgencyViewProjectList";
}

<h1>AgencyViewProjectList</h1>

<h1>Danh sách dự án</h1>

<div class="col-md-12">
    <form method="post">
        <input type="text" name="SearchKey" />
        <input type="submit" value="Tim bang ten" class="btn btn-info" />
    </form>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Địa chỉ")
            </th>
            <th>
                @Html.DisplayName("Ngày bắt đầu")
            </th>
            <th>
                @Html.DisplayName("Ngày kết thúc")
            </th>
            <th>
                @Html.DisplayName("Tên dự án")
            </th>
            <th>
                @Html.DisplayName("Mô tả")
            </th>
            <th>
                @Html.DisplayName("Trạng thái")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Project)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectLocation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectContent)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectStatus)
                </td>
                <td>
                    <a asp-page="./AgencyProjectDetails" asp-route-id="@item.Id">Chi tiết</a> |
                    <form method="post">
                        <button type="submit" name="approveButton" class="btn btn-primary" asp-page-handler="OnApprove" asp-route-id="@item.Id">Approve</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

UI/Pages/Projects/CustomerHistory.cshtml
@page
@model UI.Pages.Projects.CustomerHistoryModel

@{
    ViewData["Title"] = "CustomerHistory";
}

<div>
    <a asp-page="./ProjectsList">Back to List</a>
</div>

<h1>Lịch sử dự án đăng</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Trạng thái")
            </th>
            <th>
                @Html.DisplayName("Địa chỉ")
            </th>
            <th>
                @Html.DisplayName("Ngày bắt đầu")
            </th>
            <th>
                @Html.DisplayName("Ngày kết thúc ")
            </th>
            <th>
                @Html.DisplayName("Tên dự án")
            </th>
            <th>
                @Html.DisplayName("Mô tả")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Project) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectLocation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectContent)
            </td>
        </tr>
}
    </tbody>
</table>

<h1>Lịch sử dự án đã booking đi xem</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Tên người đặt")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Booking[0].PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Booking[0].Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Booking[0].BookingDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Booking[0].ProductId)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Booking)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BookingUserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Content)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BookingDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductId)
                </td>
            </tr>
        }
    </tbody>
</table>

UI/Pages/Projects/Details.cshtml
@page "/Project/Details/{projectId}"
@using BO.Models
@model UI.Pages.Projects.DetailsModel
@{
    int cardCount = Model.Project?.Products.Count < 4 ? Model.Project.Products.Count : 3;
}
<style>
    .carousel .carousel-item {
        height: 500px;
    }

    .carousel-item .img {
        object-fit: cover;
        image-position: center;
        position: absolute;
        top: 0;
        left: 0;
        min-height: 500px;
    }
</style>
<div id="carouselExample" class="carousel slide">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExample" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExample" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExample" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img width="50px" src="https://file4.batdongsan.com.vn/2024/03/03/20240303211226-5260_wm.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img width="auto" src="https://file4.batdongsan.com.vn/2024/03/03/20240303211222-780d_wm.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img width="auto" src="https://file4.batdongsan.com.vn/2024/03/03/20240303211219-d8aa_wm.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
@* TODO - replace wit real data *@
<h1 class="title">Tổng quan @Model.Project!.ProjectTitle <span class="badge rounded-pill bg-success">@Model.Project.ProjectStatus</span></h1>
<div class="row">
    <div class="col-8">
        <div class="row">
            <div style="position:relative">
                <div id="mainContent" class="hideContent">
                    @Model.Project.ProjectContent
                </div>
                <div style="position: absolute; bottom: 0; width: 100%">
                    <div class="gradient">&nbsp;</div>
                    <div class="show-more">
                        <a href="#">Xem thêm</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                Sản phẩm trong dự án
            </div>
            <div class="card-body overflow-auto" style="white-space: nowrap !important">
                @for (int i = 0; i < Model.Project.Products.Count; i++)
                {
                    Product product = @Model.Project.Products.ElementAt(i);
                    <div class="d-inline-block" style="width: 200px">
                        <div class="card">
                            <img class="card-img-top" src="https://file4.batdongsan.com.vn/2024/03/03/20240303211226-5260_wm.jpg" height="100px" width="auto" style="object-fit: cover"/>
                            <div class="cardd-body" style="padding: 16px">
                                <p class="card-title text-truncate">@product.ProductTitle</p>
                                <br />
                                <a class="btn btn-primary" href="/Product/Details/@product.Id">Xem thêm</a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="col-4">
        <h1>Thông tin dự án</h1>
        <div class="row" style="margin-left: 14px; line-height: 3rem;">
            <div class="col-12 row">
                <span class="col-4 fw-bold" style="margin-right: 30px">Số dự án</span>
                <span class="col">@Model.Project.Products.Count dự án</span>
            </div>
            <div class="col-12 row">
                <span class="col-4 fw-bold" style="margin-right: 30px">Địa chỉ</span>
                <span class="col">@Model.Project.ProjectLocation</span>
            </div>
            <div class="col-12 row">
                <span class="col-4 fw-bold" style="margin-right: 30px">Google maps</span>
                <span class="col"><a href="@Model.Project.ProjectGeoLocationUrl" target="_blank">Nhấn để xem chi tiết (@Model.Project.ProjectGeoLocationUrl)</a></span>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="~/js/project_list.js">
</script>

UI/Pages/Projects/InvestorCreateProjectProducts.cshtml
@page
@model UI.Pages.Projects.InvestorCreateProjectProductsModel

@{
    ViewData["Title"] = "InvestorCreateProjectProducts";
}

<h1>Tạo Dự án và các sản phẩm</h1>

<form method="post">
    <div>
        <label asp-for="Project.ProjectTitle"></label>
        <input asp-for="Project.ProjectTitle" class="form-control" />
        <span asp-validation-for="Project.ProjectTitle" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Project.ProjectLocation"></label>
        <input asp-for="Project.ProjectLocation" class="form-control" />
        <span asp-validation-for="Project.ProjectLocation" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Project.ProjectContent"></label>
        <input asp-for="Project.ProjectContent" class="form-control" />
        <span asp-validation-for="Project.ProjectContent" class="text-danger"></span>
    </div>

    <h2>Sản phẩm</h2>
    <div id="productList">
        @for (int i = 0; i < Model.Products.Count; i++)
        {
            <div class="product">
                <div>
                    <label asp-for="@Model.Products[i].ProductTitle"></label>
                    <input type="text" asp-for="@Model.Products[i].ProductTitle" class="form-control" />
                    <span asp-validation-for="@Model.Products[i].ProductTitle" class="text-danger"></span>
                </div>
                <div>
                    <label asp-for="@Model.Products[i].Address"></label>
                    <input type="text" asp-for="@Model.Products[i].Address" class="form-control" />
                    <span asp-validation-for="@Model.Products[i].Address" class="text-danger"></span>
                </div>
                <div>
                    <label asp-for="@Model.Products[i].Description"></label>
                    <input type="text" asp-for="@Model.Products[i].Description" class="form-control" />
                    <span asp-validation-for="@Model.Products[i].Description" class="text-danger"></span>
                </div>
                <div>
                    <label asp-for="@Model.Products[i].Price"></label>
                    <input type="text" asp-for="@Model.Products[i].Price" class="form-control" />
                    <span asp-validation-for="@Model.Products[i].Price" class="text-danger"></span>
                </div>
                <button type="button" class="btn btn-danger" onclick="removeProduct(this)">Remove</button>
            </div>
        }
    </div>
    <button type="button" id="addProduct" class="btn btn-primary">Add Product</button>

    <button type="submit" class="btn btn-success">Create Project</button>
</form>

@section Scripts {
    <script>
        document.getElementById('addProduct').addEventListener('click', function () {
            var productList = document.getElementById('productList');
            var productIndex = productList.children.length; // Get the current number of products
            var product = document.createElement('div');
            product.className = 'product';
            product.innerHTML = `
                    <div>
                        <label>Title</label>
                        <input type="text" name="Products[${productIndex}].ProductTitle" class="form-control" />
                    </div>
                    <div>
                        <label>Address</label>
                        <input type="text" name="Products[${productIndex}].Address" class="form-control" />
                    </div>
                    <div>
                        <label>Description</label>
                        <input type="text" name="Products[${productIndex}].Description" class="form-control" />
                    </div>
                    <div>
                        <label>Price</label>
                        <input type="text" name="Products[${productIndex}].Price" class="form-control" />
                    </div>
                    <button type="button" class="btn btn-danger" onclick="removeProduct(this)">Remove</button>
                `;
            productList.appendChild(product);
        });

        function removeProduct(element) {
            element.closest('.product').remove();
        }
    </script>
}